### ISSUE TITLE
关于iOS10推送声音的疑问

### ISSUE THREAD

**Issue by kakashilw** [wenghengcong/iOSNotifications#1]
多谢这么详细的总结！根据你的几篇教程，做了iOS10的推送的适配，并用development模式测试，能正常获取到DeviceToken，也能正常收到推送信息。。就是指定了 'sound' => 'push.caf'，在iOS9收到推送能播放自定义的声音，但是在iOS10里就不起作用了，仍然是播放系统推送声音，不知你在测试的时候，有无在iOS10里遇到这个问题。

**Comment by wenghengcong** [comment]
@kakashilw  
Hi，对你所说的问题，我这边测试了下，也复现了。

这问题应该是iOS10的bug。

[参考链接](http://stackoverflow.com/questions/39400703/ios10-custom-push-notification-sound-not-playing)

**Comment by wenghengcong** [comment]
@kakashilw 
验证，iOS10.1已经修复该问题！
